from enum import Enum

class TokenTypes(Enum):
    KEYWORD = "KEYWORD"
    OPERATOR = "OPERATOR"
    IDENTIFIER = "IDENTIFIER"
    DELIMITER = "DELIMITER"
    ESCAPE_CHARACTER = "ESCAPE_CHARACTER"
    LITERALS_TYPES = "LITERALS_TYPES"
    VAR_TYPE = "VAR_TYPE"
    SCOPE = "SCOPE"